#pragma once


enum class GameStates
{
	NONE=0, MENU, LOBBY, INITGAME, LOADING, FINISHEDLOADING, INGAME, PAUSE, RESULTS, NUMSTATES
};


enum class EnumGameDelta
{
	NOTCHANGED=0, ENTEREDTHISFRAME, EXITTHISFRAME,
};


enum class ServerStates
{
	NONE=0, LOBBY, SENTALLPACKETS, LOADING, INGAME, RESULTS, NUMSTATES
};
